name = "milli-gold-worker"
main = "cloudflare_worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

[env.production.vars]
GITHUB_TOKEN = ""

[env.staging.vars]
GITHUB_TOKEN = ""